export const brand = { name: 'Seattle Black Town Car', phone: '(206) 719-0015', email: 'info@seattleblacktowncar.com', location: 'Lynnwood, WA 98036' }
export const locations = ['Seattle-Tacoma International Airport (SEA)', 'Downtown Seattle', 'Bellevue', 'Redmond', 'Lynnwood', 'Everett', 'Boeing Field (BFI)', 'Lake Union Seaplane Base (LKE)']
export const services = [
  { id: 'airport-transfers', name: 'Airport Transfers', icon: 'plane', short: 'A calm start. A seamless arrival.', description: 'Plan your ride to or from SEA, Boeing Field, or Lake Union. Keep your flight, pickup time, and luggage needs together in one itinerary.', consideration: 'Include your flight number and allow time for baggage collection. Pickup arrangements need confirmation.', image: 'sedan', cardImage: 'airport-transfers.webp', imageAlt: 'Traveler waiting with luggage outside a modern airport terminal' },
  { id: 'airport-suv', name: 'Airport SUV Service', icon: 'car', short: 'Your flight. A little more room.', description: 'Choose an SUV class for airport journeys with more passengers or luggage. Compare the listed capacities before selecting your ride.', consideration: 'Tell us the number and size of your bags; seating and luggage share available space.', image: 'suv', cardImage: 'airport-suv-service.webp', imageAlt: 'Black premium SUV parked on a modern city street' },
  { id: 'suv-chauffeur', name: 'SUV Chauffeur Service', icon: 'car', short: 'More space for every occasion.', description: 'A private chauffeur journey for city travel, day trips, and shared itineraries, with the extra room of an SUV.', consideration: 'This is chauffeured transportation, not a self-drive rental.', image: 'suv', cardImage: 'suv-chauffeur-service.webp', imageAlt: 'Professional chauffeur holding a car door for an executive passenger' },
  { id: 'corporate', name: 'Corporate Transportation', icon: 'briefcase', short: 'Arrive ready for what’s next.', description: 'Plan travel between airports, hotels, meetings, and business events, with room to settle in along the way.', consideration: 'Include meeting times and all itinerary details when discussing your journey.', image: 'interior', cardImage: 'corporate-transportation.webp', imageAlt: 'Business traveler working from the back seat of a car' },
  { id: 'hourly', name: 'Hourly Chauffeur', icon: 'clock', short: 'Your itinerary. Your pace.', description: 'Choose a duration for a flexible itinerary, from a series of meetings to an afternoon exploring Seattle.', consideration: 'Share the intended route and duration. Actual hourly rates and availability require confirmation.', image: 'sedan', cardImage: 'hourly-chauffeur.webp', imageAlt: 'Chauffeur in a suit opening the door of a black car' },
  { id: 'events', name: 'Proms & Events', icon: 'sparkles', short: 'Make the journey part of the occasion.', description: 'Plan transportation for prom, concerts, sporting events, and evenings out, including the details that make group travel easier.', consideration: 'Confirm passenger count, event end time, and arrangements for younger passengers.', image: 'interior', cardImage: 'proms-events.webp', imageAlt: 'Young couple in formal attire beside a car before an event' },
  { id: 'weddings', name: 'Wedding Transportation', icon: 'sparkles', short: 'Every detail, beautifully considered.', description: 'Coordinate a journey for the couple or wedding guests between venues, hotels, and the celebration.', consideration: 'Discuss timing, attire, group size, and any special vehicle requests in advance.', image: 'sedan', cardImage: 'wedding-transportation.webp', imageAlt: 'Newlywed couple in formal attire standing beside a car' },
  { id: 'groups', name: 'Group & Van Transportation', icon: 'users', short: 'Good company. One journey.', description: 'Explore passenger van transportation for colleagues, families, and groups traveling together.', consideration: 'Listed van capacities are planning guides. Confirm the actual seating and luggage layout.', image: 'interior', cardImage: 'group-van-transportation.webp', imageAlt: 'Black passenger van with its side door open on a city street' },
  { id: 'family', name: 'Family Transportation', icon: 'users', short: 'Room for the people who matter.', description: 'Plan family airport transfers and outings with passenger, luggage, and child-seat requests considered from the start.', consideration: 'Child-seat and assistance requests are subject to confirmation and must be arranged in advance.', image: 'suv', cardImage: 'family-transportation.webp', imageAlt: 'Mother and daughter traveling together with luggage at an airport' },
]
export type Vehicle = { id: string; name: string; subtitle: string; passengers: number; bags: number; image: string; amenities: string[] }
export const vehicles: Vehicle[] = [
  { id: 'standard', name: 'Standard Sedan', subtitle: 'An effortless everyday arrival', passengers: 3, bags: 2, image: 'sedan', amenities: ['Private ride', 'Climate control'] },
  { id: 'business', name: 'Business Class', subtitle: 'Your space between appointments', passengers: 3, bags: 3, image: 'sedan', amenities: ['Executive seating', 'Quiet cabin'] },
  { id: 'suv', name: 'Luxury SUV', subtitle: 'Generous space. Refined comfort.', passengers: 5, bags: 5, image: 'suv', amenities: ['Spacious cabin', 'Flexible luggage space'] },
  { id: 'van', name: 'Passenger Van', subtitle: 'Bring everyone along', passengers: 10, bags: 8, image: 'interior', amenities: ['Group seating', 'Shared itinerary'] },
  { id: 'first', name: 'First Class', subtitle: 'Make the journey an occasion', passengers: 2, bags: 2, image: 'sedan', amenities: ['Premium seating', 'Refined interior'] },
]
export const faqs = [
  ['How do I plan an airport pickup?', 'Select airport arrival, enter the airport and your destination, and choose a pickup time in Seattle time. Add your flight number in the booking details. Actual pickup instructions and timing must be confirmed with the company.'],
  ['Which vehicle is right for my trip?', 'Start with your passenger and luggage counts. The fleet comparison shows illustrative capacities to help you explore. Photographs are representative and do not confirm actual fleet inventory.'],
  ['Can I request a child seat or assistance?', 'Yes. Add these requests in your trip details. Equipment and assistance availability must be confirmed before travel; no listed vehicle is represented as wheelchair accessible.'],
  ['Can I arrange an hourly ride?', 'Choose Hourly in the booking panel and set your preferred duration. Share your itinerary in the notes so the final arrangements can be discussed.'],
  ['How do I complete a reservation?', 'Review your journey and prepare a quote request, then contact the company directly to confirm pricing, availability, and final travel arrangements.'],
]
